<?php

namespace GJI\GJIBundle\Repository;

/**
 * Groupe_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Groupe_UserRepository extends \Doctrine\ORM\EntityRepository
{
}
