<?php

namespace GJI\GJIBundle\Repository;

/**
 * MemberGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
