<?php

namespace Istok\IstokBundle\Repository;

/**
 * accoudoirsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accoudoirsRepository extends \Doctrine\ORM\EntityRepository
{
}
