<?php

namespace Istok\IstokBundle\Repository;

/**
 * banquette_coin_traRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class banquette_coin_traRepository extends \Doctrine\ORM\EntityRepository
{
}
