<?php

namespace Istok\IstokBundle\Repository;

/**
 * boisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class boisRepository extends \Doctrine\ORM\EntityRepository
{
}
