<?php

namespace Istok\IstokBundle\Repository;

/**
 * cat_banquettesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cat_banquettesRepository extends \Doctrine\ORM\EntityRepository
{
}
