<?php

namespace Istok\IstokBundle\Repository;

/**
 * cat_tissusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cat_tissusRepository extends \Doctrine\ORM\EntityRepository
{
}
