<?php

namespace Istok\IstokBundle\Repository;

/**
 * cendrieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cendrieRepository extends \Doctrine\ORM\EntityRepository
{
}
