<?php

namespace Istok\IstokBundle\Repository;

/**
 * coinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coinsRepository extends \Doctrine\ORM\EntityRepository
{
}
