<?php

namespace Istok\IstokBundle\Repository;

/**
 * colorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class colorRepository extends \Doctrine\ORM\EntityRepository
{
}
