<?php

namespace Istok\IstokBundle\Repository;

/**
 * dosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dosRepository extends \Doctrine\ORM\EntityRepository
{
}
