<?php

namespace Istok\IstokBundle\Repository;

/**
 * etabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class etabRepository extends \Doctrine\ORM\EntityRepository
{
}
