<?php

namespace Istok\IstokBundle\Repository;

/**
 * faceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faceRepository extends \Doctrine\ORM\EntityRepository
{
}
