<?php

namespace Istok\IstokBundle\Repository;

/**
 * faciliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faciliteRepository extends \Doctrine\ORM\EntityRepository
{
}
