<?php

namespace Istok\IstokBundle\Repository;

/**
 * factureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class factureRepository extends \Doctrine\ORM\EntityRepository
{
}
