<?php

namespace Istok\IstokBundle\Repository;

/**
 * fcoinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fcoinsRepository extends \Doctrine\ORM\EntityRepository
{
}
