<?php

namespace Istok\IstokBundle\Repository;

/**
 * ligne_cmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligne_cmdRepository extends \Doctrine\ORM\EntityRepository
{
}
