<?php

namespace Istok\IstokBundle\Repository;

/**
 * midaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class midaRepository extends \Doctrine\ORM\EntityRepository
{
}
