<?php

namespace Istok\IstokBundle\Repository;

/**
 * organisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class organisationRepository extends \Doctrine\ORM\EntityRepository
{
}
