<?php

namespace Istok\IstokBundle\Repository;

/**
 * parametresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parametresRepository extends \Doctrine\ORM\EntityRepository
{
}
