<?php

namespace Istok\IstokBundle\Repository;

/**
 * sous_banquettesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sous_banquettesRepository extends \Doctrine\ORM\EntityRepository
{
}
