<?php

namespace Istok\IstokBundle\Repository;

/**
 * tissusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tissusRepository extends \Doctrine\ORM\EntityRepository
{
}
