<?php

namespace Istok\IstokBundle\Repository;

/**
 * venteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class venteRepository extends \Doctrine\ORM\EntityRepository
{
}
